//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace camdochieuduong.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CauHinh
    {
        public string Type { get; set; }
        public Nullable<decimal> LaiDuoi10Tr { get; set; }
        public Nullable<decimal> LaiTren10Tr { get; set; }
        public Nullable<decimal> SoNgayApDung { get; set; }
        public Nullable<decimal> SoNgayToiHan { get; set; }
    }
}
