//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace camdochieuduong.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoDich
    {
        public string IDBienNhan { get; set; }
        public Nullable<System.DateTime> NgayCam { get; set; }
        public string KhachHang { get; set; }
        public string DienThoai { get; set; }
        public string MoTa { get; set; }
        public Nullable<decimal> GiaTri { get; set; }
        public Nullable<decimal> TienCam { get; set; }
        public string TruHotCon { get; set; }
        public Nullable<decimal> InBienNhan { get; set; }
        public string Canceled { get; set; }
        public string ThayTheCho { get; set; }
        public string ThayTheBang { get; set; }
        public string DonGoc { get; set; }
        public string DaChuoc { get; set; }
        public string BaoMat { get; set; }
        public Nullable<decimal> TienLai { get; set; }
        public string LoaiGiaoDich { get; set; }
    }
}
