//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace camdochieuduong.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThuChi
    {
        public int MaThuChi { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public Nullable<decimal> SoTien { get; set; }
        public string MoTa { get; set; }
        public string Cancel { get; set; }
        public string LoaiGiaoDich { get; set; }
    }
}
